export const PATHS = {
	home: '/',
	loginAdmin: '/loginAdmin',
	loginParticipant: '/loginParticipant',
	tournament: '/tournaments',
	tournamentDetails: '/tournament/:number',
	groupDetails: '/group/:number',
	finals: '/finals/:number',
	register: '/register',
	fight: '/fight/:number',
	participant: '/participant/:number',
	addParticipant: '/addParticipant/:number',
	editParticipant: '/editParticipant/:number',
	editFight: '/editFight/:number',
	fightReport: '/fightReport/:number',
	reports: '/reports',
	report: '/report/:number',
}
